### PR TITLE
Add versionwarning to old docs pages

### PR DESCRIPTION
**Pull request by drammock**
WIP, doing one doc version per commit because my laptop / editor can't handle changing 3k files all at once.

### CODE REVIEW

**Comment by larsoner** [comment]
@drammock just want me to run locally so that you don't have to kill your laptop:
```
find ./0.11/ -name "*.html" -type f -exec sed -i '/<\/footer>/a <script src="../versionwarning.js"></script>' {} \;
...
```

**Comment by larsoner** [comment]
... also maybe we should use the relative path `../` (as in my snippet) instead of absolute `mne.tools` in case we ever switch domains or anything?

**Comment by larsoner** [comment]
I see you have committed them all -- If you agree it should be a relative link I can do this easily with a `find/sed` in a follow-up commit. Or we can just wait to do it until we need it I suppose...

**Comment by drammock** [comment]
> ... also maybe we should use the relative path `../` (as in my snippet) instead of absolute `mne.tools` in case we ever switch domains or anything?

relative path won't work on sub-pages, like mne.tools/0.19/auto_tutorials/intro/plot_whatever.html

**Comment by larsoner** [comment]
Looks like maybe `/versionwarning.js` should work. Not sure if it's worth it or not?

**Comment by drammock** [comment]
> Looks like maybe `/versionwarning.js` should work. Not sure if it's worth it or not?

now that we have mne.tools what are the odds the URL will change again?  If you think it's a realistic worry, feel free to push here.

One other question: I've altered the files in `/stable` too, so that when the next release goes out, they'll automatically start showing the warning.  However, this will be a problem if any more backports happen.  So we can either declare "no more point releases on 0.20" or we can revert the 2 commits here that affect `/stable` and get them into 0.20 by backporting the changes to `layout.html`.

**Comment by larsoner** [comment]
> However, this will be a problem if any more backports happen. So we can either declare "no more point releases on 0.20" or we can revert the 2 commits here that affect /stable and get them into 0.20 by backporting the changes to layout.html.

Another solution would be to open a PR to `maint/0.20` in MNE to add it, then CircleCI will take care of `0.20` for us

**Comment by larsoner** [comment]
you could even direct push to maint/0.20 with a `[ci skip]` if you want now that I've merged the 0.20 changes in with this PR

**Pull request merged**
