### PR TITLE
Update to 0.11.

### PR DESCRIPTION
**Pull request by jaeilepp**

### CODE REVIEW

**Comment by agramfort** [comment]
can you update also the stable branch using maint/0.11 branch?

when done please merge so we can send the announcement email.

thanks heaps @jaeilepp !

**Comment by jaeilepp** [comment]
I think the stable is updated too. It just doesn't show on the diff because it's too large. Merging.

**Comment by agramfort** [comment]
I updated the website but I see a few issues in the gallery. For example:

http://martinos.org/mne/dev/auto_examples/preprocessing/plot_shift_evoked.html#sphx-glr-auto-examples-preprocessing-plot-shift-evoked-py

says "../examples/preprocessing/plot_shift_evoked.py is not compiling:"

**Comment by jasmainak** [comment]
also noticed that the examples here don't link correctly: http://www.martinos.org/mne/dev/manual/preprocessing/ssp.html#delayed-projectors

I remember they worked fine when I built them ... maybe I was using old links (not sure ...)

**Comment by jaeilepp** [comment]
Which links? They seem to work for me.
My testing dataset was somehow wrong. Downloading new data now. Seems to take ages on my parents' internet connection.

**Comment by jasmainak** [comment]
This thing
- [example_visualization_plot_evoked_delayed_ssp.py](http://www.martinos.org/mne/dev/auto_examples/visualization/plot_evoked_delayed_ssp.html#sphx-glr-auto-examples-visualization-plot-evoked-delayed-ssp-py): Interactive SSP
- [example_visualization_plot_evoked_topomap_delayed_ssp.py](http://www.martinos.org/mne/dev/auto_examples/visualization/plot_evoked_topomap_delayed_ssp.html#sphx-glr-auto-examples-visualization-plot-evoked-topomap-delayed-ssp-py): Interactive SSP
- [example_visualization_plot_ssp_projs_topomaps.py](http://www.martinos.org/mne/dev/auto_examples/visualization/plot_ssp_projs_topomaps.html#sphx-glr-auto-examples-visualization-plot-ssp-projs-topomaps-py): SSP sensitivities in sensor space
- [example_visualization_plot_ssp_projs_sensitivity_map.py](http://www.martinos.org/mne/dev/auto_examples/visualization/plot_ssp_projs_sensitivity_map.html#sphx-glr-auto-examples-visualization-plot-ssp-projs-sensitivity-map-py): SSP sensitivities in source space

**Comment by Eric89GXL** [comment]
> My testing dataset was somehow wrong. Downloading new data now. Seems to
take ages on my parents' internet connection.

That dataset gets updated fairly frequently. But it also isn't really
designed for users / examples. We should switch any examples that currently
use it to use sample instead if we can.

**Comment by agramfort** [comment]
> That dataset gets updated fairly frequently. But it also isn't really
> designed for users / examples. We should switch any examples that currently
> use it to use sample instead if we can.

+1

**Comment by agramfort** [comment]
indeed links are still broken. crap.

what version of sphinx and sphinx-gallery are you guys using?

you should be using the latest master from sphinx-gallery and the last
release of sphinx you can get with pip.

**Comment by jasmainak** [comment]
It seems to me that sphinx-gallery changed the way how the examples are cross-referenced. It breaks things. I see two types of headers in my auto_examples/ dir. It's either :ref:`example_visualization_plot_ssp_projs_sensitivity_map.py` or :ref:`sphx_glr_auto_examples_decoding_plot_decoding_sensors.py`

Maybe that's causing the issue?

**Comment by agramfort** [comment]
yeah maybe a pb of sphinx gallery versions...

let's make sure it works with latest master

**Pull request merged**
